# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	GNU binary tools for MinGW-w64 x86_64

PORT_TYPE=	x86_64
MASTERDIR=	${.CURDIR}/../mingw-multilib-binutils

.include "${MASTERDIR}/Makefile"
