# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	GNU binary tools for MinGW-w64 i686

PORT_TYPE=	i686
MASTERDIR=	${.CURDIR}/../mingw-multilib-binutils

.include "${MASTERDIR}/Makefile"
