# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	GCC 4.9 for MinGW-w64 bootstrap

PKGNAMESUFFIX?=	-bootstrap
MASTERDIR=	${.CURDIR}/../mingw64-gcc

.include "${MASTERDIR}/Makefile"
