# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

MAINTAINER=	takumiiinn@gmail.com
COMMENT?=	GNU Compiler Collection for MinGW-w64

PKGNAMESUFFIX?=	-bootstrap
MASTERDIR=	${.CURDIR}/../mingw64-gcc

.include "${MASTERDIR}/Makefile"
