# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	MinGW-w64 for getpid replacement using GetCurrentProcessId

PKGNAMESUFFIX=	-winstorecompat
MASTERDIR=	${.CURDIR}/../mingw64-crt

.include "${MASTERDIR}/Makefile"
