# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	MinGW-w64 for translating C++ symbols produced by MS VC++

PKGNAMESUFFIX=	-libmangle
MASTERDIR=	${.CURDIR}/../mingw64-crt

.include "${MASTERDIR}/Makefile"
