# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	MinGW-w64 for header files

PKGNAMESUFFIX=	-headers
MASTERDIR=	${.CURDIR}/../mingw-w64-crt

.include "${MASTERDIR}/Makefile"
