# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	MinGW-w64 for i686 header files

PORT_ARCH=	i686
PORT_TYPE=	headers
MASTERDIR=	${.CURDIR}/../mingw-w64-multilib-crt

.include "${MASTERDIR}/Makefile"
