# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	GCC 4.9 for MinGW-w64 x86_64 bootstrap

PORT_TYPE?=	bootstrap
PORT_ARCH?=	multilib
THREADS_TYPE?=	win32
EXEPTION_TYPE?=	dwarf2

MASTERDIR=	${.CURDIR}/../mingw-multilib-gcc-win32-seh

.include "${MASTERDIR}/Makefile"
