# Created by: Takumi Takahashi <takumiiinn@gmail.com>
# $FreeBSD$

MAINTAINER=	takumiiinn@gmail.com
COMMENT=	MinGW-w64 for POSIX threads library

PKGNAMESUFFIX=	-winpthreads
MASTERDIR=	${.CURDIR}/../mingw64-crt

.include "${MASTERDIR}/Makefile"
